REM constraints.sql
REM (c) Go-Faster Consultancy Ltd. 2004

DROP TABLE tab1;
CREATE TABLE tab1(a NUMBER,b NUMBER,c NUMBER,d NUMBER);
CREATE UNIQUE INDEX idx1 ON tab1(a,b,c);
INSERT INTO tab1 (a,b) VALUES(1,1);
--ALTER SESSION SET TRACEFILE_IDENTIFIER = 'idx';
--ALTER SESSION SET EVENTS '10046 trace name context forever, level 8';
INSERT INTO tab1 (a,b) VALUES(1,1);
--ALTER SESSION SET SQL_TRACE=FALSE;

ALTER TABLE tab1 ADD CONSTRAINT con1 UNIQUE(a,b,c) USING INDEX idx1;
--ALTER SESSION SET TRACEFILE_IDENTIFIER = 'con';
--ALTER SESSION SET EVENTS '10046 trace name context forever, level 8';
INSERT INTO tab1 (a,b) VALUES(1,1);
--ALTER SESSION SET SQL_TRACE=FALSE;

ALTER TABLE tab1 ADD CONSTRAINT con2 UNIQUE(a,b,c);
ALTER TABLE tab1 DROP CONSTRAINT con1 KEEP INDEX;
INSERT INTO tab1 (a,b) VALUES(1,1);
DROP TABLE tab1;

