--select pm_metricid, pm_metriclabel, length(pm_metriclabel)
--from   pspmmetricdefn m
--,      pspmeventdefn e
--where  e.pm_event_defn_id IN(152,153)
--and    m.pm_metricid IN(e.pm_metricid_1,e.pm_metricid_2,e.pm_metricid_3,
--        e.pm_metricid_4,e.pm_metricid_5,e.pm_metricid_6,e.pm_metricid_7);


alter session set nls_date_format = 'hh24:mi:ss dd.mm.yyyy';
set pages 100 trimspool on lines 70
column DBNAME          format a5
column PM_HOST_PORT    format a21
column PM_AGENT_TYPE   format a13
column PM_INSTANCE_ID  format 9999999999999
column PM_DOMAIN_NAME  format a14
column PM_METRICLABEL1 format a30
column PM_METRICLABEL2 format a30
column PM_METRICLABEL3 format a30
column PM_METRICLABEL4 format a30
column PM_METRICLABEL5 format a30
column PM_METRICLABEL6 format a30
column PM_METRICLABEL7 format a30
column PM_METRIC_VALUE7 format a20

break on DBNAME on PM_HOST_PORT on PM_AGENT_TYPE on PM_DOMAIN_NAME on PM_AGENT_DTTM on PM_EVENT_DEFN_ID on DESCR60
clear screen
spool ev153

SELECT DBNAME, 
       PM_HOST_PORT, 
--     PM_AGENT_TYPE, 
--     PM_DOMAIN_NAME, 
--     PM_INSTANCE, 
       PM_AGENT_DTTM,
--     PM_INSTANCE_ID, 
       PM_EVENT_DEFN_ID, DESCR60,
       PM_METRICLABEL1, CASE 
         WHEN PM_METRICTYPE1 = '1' AND PM_METRIC_VALUE1<PM_METRIC_LAST1 THEN PM_METRIC_VALUE1
         WHEN PM_METRICTYPE1 = '1' THEN PM_METRIC_VALUE1-PM_METRIC_LAST1
         ELSE PM_METRIC_VALUE1
       END AS PM_METRIC_VALUE1,
       PM_METRICLABEL2, CASE 
         WHEN PM_METRICTYPE2 = '1' AND PM_METRIC_VALUE2<PM_METRIC_LAST2 THEN PM_METRIC_VALUE2
         WHEN PM_METRICTYPE2 = '1' THEN PM_METRIC_VALUE2-PM_METRIC_LAST2
         ELSE PM_METRIC_VALUE2
       END AS PM_METRIC_VALUE2,
       PM_METRICLABEL3, CASE 
         WHEN PM_METRICTYPE3 = '1' AND PM_METRIC_VALUE3<PM_METRIC_LAST3 THEN PM_METRIC_VALUE3
         WHEN PM_METRICTYPE3 = '1' THEN PM_METRIC_VALUE3-PM_METRIC_LAST3
         ELSE PM_METRIC_VALUE3
       END AS PM_METRIC_VALUE3,
       PM_METRICLABEL4, CASE 
         WHEN PM_METRICTYPE4 = '1' AND PM_METRIC_VALUE4<PM_METRIC_LAST4 THEN PM_METRIC_VALUE4
         WHEN PM_METRICTYPE4 = '1' THEN PM_METRIC_VALUE4-PM_METRIC_LAST4
         ELSE PM_METRIC_VALUE4
       END AS PM_METRIC_VALUE4 /*,
       PM_METRICLABEL5, CASE 
         WHEN PM_METRICTYPE5 = '1' AND PM_METRIC_VALUE5<PM_METRIC_LAST5 THEN PM_METRIC_VALUE5
         WHEN PM_METRICTYPE5 = '1' THEN PM_METRIC_VALUE5-PM_METRIC_LAST5
         ELSE PM_METRIC_VALUE5
       END AS PM_METRIC_VALUE5,
       PM_METRICLABEL6, CASE 
         WHEN PM_METRICTYPE6 = '1' AND PM_METRIC_VALUE6<PM_METRIC_LAST6 THEN PM_METRIC_VALUE6
         WHEN PM_METRICTYPE6 = '1' THEN PM_METRIC_VALUE6-PM_METRIC_LAST6
         ELSE PM_METRIC_VALUE6
       END AS PM_METRIC_VALUE6*/
,       PM_METRICLABEL7, PM_METRIC_VALUE7
--,       PM_ADDTNL_DESCR
FROM   (
SELECT B.DBNAME, 
       A.PM_HOST_PORT, A.PM_AGENT_TYPE, A.PM_DOMAIN_NAME, A.PM_INSTANCE, 
       C.PM_AGENT_DTTM,
       C.PM_INSTANCE_ID, 
       E.PM_EVENT_DEFN_ID, E.DESCR60,
       NVL(M1.PM_METRICLABEL,'1Unused') PM_METRICLABEL1 ,C.PM_METRIC_VALUE1, LEAD(C.PM_METRIC_VALUE1,1) OVER(PARTITION BY C.PM_AGENTID,C.PM_METRIC_VALUE7 ORDER BY C.PM_AGENT_DTTM DESC) AS PM_METRIC_LAST1,
       NVL(M2.PM_METRICLABEL,'2Unused') PM_METRICLABEL2 ,C.PM_METRIC_VALUE2, LEAD(C.PM_METRIC_VALUE2,1) OVER(PARTITION BY C.PM_AGENTID,C.PM_METRIC_VALUE7 ORDER BY C.PM_AGENT_DTTM DESC) AS PM_METRIC_LAST2,
       NVL(M3.PM_METRICLABEL,'3Unused') PM_METRICLABEL3 ,C.PM_METRIC_VALUE3, LEAD(C.PM_METRIC_VALUE3,1) OVER(PARTITION BY C.PM_AGENTID,C.PM_METRIC_VALUE7 ORDER BY C.PM_AGENT_DTTM DESC) AS PM_METRIC_LAST3,
       NVL(M4.PM_METRICLABEL,'4Unused') PM_METRICLABEL4 ,C.PM_METRIC_VALUE4, LEAD(C.PM_METRIC_VALUE4,1) OVER(PARTITION BY C.PM_AGENTID,C.PM_METRIC_VALUE7 ORDER BY C.PM_AGENT_DTTM DESC) AS PM_METRIC_LAST4,
       NVL(M5.PM_METRICLABEL,'5Unused') PM_METRICLABEL5 ,C.PM_METRIC_VALUE5, LEAD(C.PM_METRIC_VALUE5,1) OVER(PARTITION BY C.PM_AGENTID,C.PM_METRIC_VALUE7 ORDER BY C.PM_AGENT_DTTM DESC) AS PM_METRIC_LAST5,
       NVL(M6.PM_METRICLABEL,'6Unused') PM_METRICLABEL6 ,C.PM_METRIC_VALUE6, LEAD(C.PM_METRIC_VALUE6,1) OVER(PARTITION BY C.PM_AGENTID,C.PM_METRIC_VALUE7 ORDER BY C.PM_AGENT_DTTM DESC) AS PM_METRIC_LAST6,
       NVL(M7.PM_METRICLABEL,'7Unused') PM_METRICLABEL7 ,C.PM_METRIC_VALUE7, LEAD(C.PM_METRIC_VALUE7,1) OVER(PARTITION BY C.PM_AGENTID,C.PM_METRIC_VALUE7 ORDER BY C.PM_AGENT_DTTM DESC) AS PM_METRIC_LAST7,
       C.PM_ADDTNL_DESCR,
       M1.PM_METRICTYPE PM_METRICTYPE1,
       M2.PM_METRICTYPE PM_METRICTYPE2,
       M3.PM_METRICTYPE PM_METRICTYPE3,
       M4.PM_METRICTYPE PM_METRICTYPE4,
       M5.PM_METRICTYPE PM_METRICTYPE5,
       M6.PM_METRICTYPE PM_METRICTYPE6,
       M7.PM_METRICTYPE PM_METRICTYPE7
FROM   PSPMAGENT A, PSPMSYSDEFN B, PSPMEVENTHIST C, PSPMEVENTDEFN E, 
       PSPMMETRICDEFN M1, PSPMMETRICDEFN M2, PSPMMETRICDEFN M3,
       PSPMMETRICDEFN M4, PSPMMETRICDEFN M5, PSPMMETRICDEFN M6,
       PSPMMETRICDEFN M7
WHERE  B.PM_SYSTEMID = A.PM_SYSTEMID 
AND    A.PM_AGENTID = C.PM_AGENTID 
AND    B.DBNAME IN ('HR88' ,'hr88')
AND    C.PM_EVENT_DEFN_SET = E.PM_EVENT_DEFN_SET 
AND    C.PM_EVENT_DEFN_ID = E.PM_EVENT_DEFN_ID 
AND    M1.PM_METRICID(+) = E.PM_METRICID_1 
AND    M2.PM_METRICID(+) = E.PM_METRICID_2 
AND    M3.PM_METRICID(+) = E.PM_METRICID_3 
AND    M4.PM_METRICID(+) = E.PM_METRICID_4
AND    M5.PM_METRICID(+) = E.PM_METRICID_5 
AND    M6.PM_METRICID(+) = E.PM_METRICID_6 
AND    M7.PM_METRICID(+) = E.PM_METRICID_7 
AND    E.PM_EVENT_DEFN_SET = 1 
AND    E.PM_EVENT_DEFN_ID = 153
AND    C.PM_AGENT_DTTM BETWEEN TO_DATE('200408241643','yyyymmddhh24mi')
                           AND TO_DATE('200408241700','yyyymmddhh24mi')
ORDER BY C.PM_AGENT_DTTM DESC
       ) C
WHERE  C.PM_AGENT_DTTM BETWEEN TO_DATE('200408241653','yyyymmddhh24mi')
                           AND TO_DATE('200408241700','yyyymmddhh24mi')
AND    C.PM_METRIC_VALUE1 > 0
ORDER BY PM_AGENT_DTTM
;
spool off
