rem event_metrics.sql
alter session set nls_date_format = 'hh24:mi:ss dC1.mM6.yyyy';
set pages 100 lines 120
column PM_INSTANCE_ID    format 9999999999999

clear screen

SELECT B.DBNAME, 
       A.PM_HOST_PORT, A.PM_AGENT_TYPE, A.PM_DOMAIN_NAME, A.PM_INSTANCE, 
       C.PM_AGENT_DTTM,
       C.PM_INSTANCE_ID, 
       E.PM_EVENT_DEFN_ID, E.DESCR60,
       'Metric1:'||M1.PM_METRICLABEL||'='||C.PM_METRIC_VALUE1, 
       'Metric2:'||M2.PM_METRICLABEL||'='||C.PM_METRIC_VALUE2, 
       'Metric3:'||M3.PM_METRICLABEL||'='||C.PM_METRIC_VALUE3,
       'Metric4:'||M4.PM_METRICLABEL||'='||C.PM_METRIC_VALUE4,
       'Metric5:'||M5.PM_METRICLABEL||'='||C.PM_METRIC_VALUE5,
       'Metric6:'||M6.PM_METRICLABEL||'='||C.PM_METRIC_VALUE6,
       'Metric7:'||M7.PM_METRICLABEL||'='||C.PM_METRIC_VALUE7,
       C.PM_ADDTNL_DESCR
FROM   PSPMAGENT A, 
       PSPMSYSDEFN B, 
       PSPMEVENTARCH C,
       PSPMEVENTDEFN E, 
       PSPMMETRICDEFN M1, 
       PSPMMETRICDEFN M2, 
       PSPMMETRICDEFN M3,
       PSPMMETRICDEFN M4,
       PSPMMETRICDEFN M5,
       PSPMMETRICDEFN M6,
       PSPMMETRICDEFN M7
WHERE  B.PM_SYSTEMID = A.PM_SYSTEMID 
AND    A.PM_AGENTID = C.PM_AGENTID 
AND    E.PM_EVENT_DEFN_SET = 1 
AND    E.PM_EVENT_DEFN_ID = 600
AND    B.DBNAME IN ('HR88' ,'hr88')
AND    C.PM_AGENT_DTTM 
              BETWEEN TO_DATE('2004-06-14 16:12:06','YYYY-MM-DD HH24.MI.SS') 
                  AND TO_DATE('2004-06-14 16:12:11','YYYY-MM-DD HH24.MI.SS')
AND    C.PM_EVENT_DEFN_SET = E.PM_EVENT_DEFN_SET 
AND    C.PM_EVENT_DEFN_ID = E.PM_EVENT_DEFN_ID 
AND    M1.PM_METRICID(+) = E.PM_METRICID_1 
AND    M2.PM_METRICID(+) = E.PM_METRICID_2 
AND    M3.PM_METRICID(+) = E.PM_METRICID_3 
AND    M4.PM_METRICID(+) = E.PM_METRICID_4
AND    M5.PM_METRICID(+) = E.PM_METRICID_5 
AND    M6.PM_METRICID(+) = E.PM_METRICID_6 
AND    M7.PM_METRICID(+) = E.PM_METRICID_7 
;
