alter session set nls_date_format = 'hh24:mi:ss dC1.mM6.yyyy';
set pages 100 lines 120
column PM_INSTANCE_ID    format 9999999999999

clear screen
SELECT E.PM_EVENT_DEFN_SET, E.PM_EVENT_DEFN_ID
,      E.DESCR60
,      E.PM_EVENT_LABEL
,      E.PM_ADDTNL_LABEL
,      '1:'||E.PM_METRICID_1||'='||M1.PM_METRICLABEL, M1.PM_METRICTYPE, X1.XLATLONGNAME
,      '2:'||E.PM_METRICID_2||'='||M2.PM_METRICLABEL, M2.PM_METRICTYPE, X2.XLATLONGNAME
,      '3:'||E.PM_METRICID_3||'='||M3.PM_METRICLABEL, M3.PM_METRICTYPE, X3.XLATLONGNAME
,      '4:'||E.PM_METRICID_4||'='||M4.PM_METRICLABEL, M4.PM_METRICTYPE, X4.XLATLONGNAME
,      '5:'||E.PM_METRICID_5||'='||M5.PM_METRICLABEL, M5.PM_METRICTYPE, X5.XLATLONGNAME
,      '6:'||E.PM_METRICID_6||'='||M6.PM_METRICLABEL, M6.PM_METRICTYPE, X6.XLATLONGNAME
,      '7:'||E.PM_METRICID_7||'='||M7.PM_METRICLABEL, M7.PM_METRICTYPE, X7.XLATLONGNAME
--       E.PM_FILTER_LEVEL
--       E.PM_SAMPLING_ENABLE
FROM   PSPMEVENTDEFN E
,      PSPMMETRICDEFN M1
,      PSPMMETRICDEFN M2 
,      PSPMMETRICDEFN M3
,      PSPMMETRICDEFN M4
,      PSPMMETRICDEFN M5
,      PSPMMETRICDEFN M6
,      PSPMMETRICDEFN M7
,      PSXLATITEM X1
,      PSXLATITEM X2
,      PSXLATITEM X3
,      PSXLATITEM X4
,      PSXLATITEM X5
,      PSXLATITEM X6
,      PSXLATITEM X7
WHERE  M1.PM_METRICID(+) = E.PM_METRICID_1 
AND    M2.PM_METRICID(+) = E.PM_METRICID_2 
AND    M3.PM_METRICID(+) = E.PM_METRICID_3 
AND    M4.PM_METRICID(+) = E.PM_METRICID_4
AND    M5.PM_METRICID(+) = E.PM_METRICID_5 
AND    M6.PM_METRICID(+) = E.PM_METRICID_6 
AND    M7.PM_METRICID(+) = E.PM_METRICID_7 
AND    X1.FIELDNAME(+) = 'PM_METRICTYPE'
AND    X2.FIELDNAME(+) = 'PM_METRICTYPE'
AND    X3.FIELDNAME(+) = 'PM_METRICTYPE'
AND    X4.FIELDNAME(+) = 'PM_METRICTYPE'
AND    X5.FIELDNAME(+) = 'PM_METRICTYPE'
AND    X6.FIELDNAME(+) = 'PM_METRICTYPE'
AND    X7.FIELDNAME(+) = 'PM_METRICTYPE'
AND    X1.FIELDVALUE(+) = M1.PM_METRICTYPE
AND    X2.FIELDVALUE(+) = M2.PM_METRICTYPE
AND    X3.FIELDVALUE(+) = M3.PM_METRICTYPE
AND    X4.FIELDVALUE(+) = M4.PM_METRICTYPE
AND    X5.FIELDVALUE(+) = M5.PM_METRICTYPE
AND    X6.FIELDVALUE(+) = M6.PM_METRICTYPE
AND    X7.FIELDVALUE(+) = M7.PM_METRICTYPE
--AND    E.PM_EVENT_DEFN_ID IN(150,152,153,300,301,302,350,351,600,601)
ORDER BY E.PM_EVENT_DEFN_ID
;


update pspmmetricdefn /*for event 200, 302*/
set pm_metrictype = '1' /*was 3(number identifier) should be 1 (counter)*/
where pm_metricid IN(103,115)
;
