rem transaction_metrics.sql
alter session set nls_date_format = 'hh24:mi:ss dd.mm.yyyy';
set pages 100 lines 120
column PM_TOP_INST_ID    format 9999999999999
column PM_INSTANCE_ID    format 9999999999999
column PM_PARENT_INST_ID format 9999999999999
clear screen

SELECT C.PM_TOP_INST_ID, C.PM_INSTANCE_ID, C.PM_PARENT_INST_ID
,      B.DBNAME
,      A.PM_HOST_PORT, A.PM_DOMAIN_NAME, A.PM_AGENT_TYPE, A.PM_INSTANCE
,      C.PM_AGENT_STRT_DTTM, C.PM_MON_STRT_DTTM
,      C.OPRID, C.PM_PERF_TRACE, C.PM_PROCESS_ID
,      E.PM_TRANS_DEFN_ID, E.DESCR60
,      'Context1:'||c.pm_contextid_1||'-'||C1.PM_CONTEXT_LABEL||'='||C.PM_CONTEXT_VALUE1
,      'Context2:'||c.pm_contextid_2||'-'||C2.PM_CONTEXT_LABEL||'='||C.PM_CONTEXT_VALUE2 
,      'Context3:'||c.pm_contextid_3||'-'||C3.PM_CONTEXT_LABEL||'='||C.PM_CONTEXT_VALUE3 
,      C.PM_TRANS_DURATION
,      'Metric1:'||M1.PM_METRICLABEL||'='||C.PM_METRIC_VALUE1
,      'Metric2:'||M2.PM_METRICLABEL||'='||C.PM_METRIC_VALUE2 
,      'Metric3:'||M3.PM_METRICLABEL||'='||C.PM_METRIC_VALUE3
,      'Metric4:'||M4.PM_METRICLABEL||'='||C.PM_METRIC_VALUE4
,      'Metric5:'||M5.PM_METRICLABEL||'='||C.PM_METRIC_VALUE5
,      'Metric6:'||M6.PM_METRICLABEL||'='||C.PM_METRIC_VALUE6
,      'Metric7:'||M7.PM_METRICLABEL||'='||C.PM_METRIC_VALUE7
,      C.PM_ADDTNL_DESCR
FROM   PSPMAGENT A, 
       PSPMSYSDEFN B, 
       PSPMTRANSARCH C,
       PSPMTRANSDEFN E, 
       PSPMMETRICDEFN M1, 
       PSPMMETRICDEFN M2, 
       PSPMMETRICDEFN M3, 
       PSPMMETRICDEFN M4, 
       PSPMMETRICDEFN M5, 
       PSPMMETRICDEFN M6, 
       PSPMMETRICDEFN M7, 
       PSPMCONTEXTDEFN C1, 
       PSPMCONTEXTDEFN C2, 
       PSPMCONTEXTDEFN C3
WHERE B.PM_SYSTEMID = A.PM_SYSTEMID 
AND   A.PM_AGENTID = C.PM_AGENTID 
AND   B.DBNAME IN ('HR88' ,'hr88')
--AND   C.PM_TRANS_DEFN_SET = 1 
--AND   C.PM_TRANS_DEFN_ID = 400
--AND   C.PM_METRIC_VALUE1 > 0 
--AND   C.PM_AGENT_DTTM 
--              BETWEEN TO_DATE('2004-06-14 16:12:06','YYYY-MM-DD HH24.MI.SS') 
--                  AND TO_DATE('2004-06-14 16:12:11','YYYY-MM-DD HH24.MI.SS')
AND   C.PM_TOP_INST_ID = 824633721163
AND   C.PM_TRANS_DEFN_SET = E.PM_TRANS_DEFN_SET 
AND   C.PM_TRANS_DEFN_ID = E.PM_TRANS_DEFN_ID 
AND   M1.PM_METRICID(+) = E.PM_METRICID_1 
AND   M2.PM_METRICID(+) = E.PM_METRICID_2 
AND   M3.PM_METRICID(+) = E.PM_METRICID_3 
AND   M4.PM_METRICID(+) = E.PM_METRICID_4
AND   M5.PM_METRICID(+) = E.PM_METRICID_5 
AND   M6.PM_METRICID(+) = E.PM_METRICID_6 
AND   M7.PM_METRICID(+) = E.PM_METRICID_7 
AND   C1.PM_CONTEXTID(+) = C.PM_CONTEXTID_1 
AND   C2.PM_CONTEXTID(+) = C.PM_CONTEXTID_2 
AND   C3.PM_CONTEXTID(+) = C.PM_CONTEXTID_3
;


