
CREATE OR REPLACE TRIGGER SYSADM.psprcsrqst_archive

before delete on SYSADM.psprcsrqst

for each row

begin

   insert into SYSADM.ps_prcsrqstarch

   (PRCSINSTANCE
   ,JOBINSTANCE
   ,MAINJOBINSTANCE
   ,PRCSJOBSEQ
   ,PRCSJOBNAME
   ,PRCSTYPE
   ,PRCSNAME
   ,PRCSITEMLEVEL
   ,MAINJOBNAME
   ,MAINJOBSEQ
   ,RUNLOCATION
   ,OPSYS
   ,DBTYPE
   ,DBNAME
   ,SERVERNAMERQST
   ,SERVERNAMERUN
   ,RUNDTTM
   ,RECURNAME
   ,OPRID
   ,PRCSVERSION
   ,RUNSTATUS
   ,RQSTDTTM
   ,LASTUPDDTTM

   ,BEGINDTTM
   ,ENDDTTM
   ,RUNCNTLID
   ,PRCSRTNCD
   ,CONTINUEJOB
   ,USERNOTIFIED
   ,INITIATEDNEXT
   ,OUTDESTTYPE
   ,OUTDESTFORMAT
   ,ORIGPRCSINSTANCE
   ,GENPRCSTYPE
   ,RESTARTENABLED
   ,TIMEZONE
   ,PSRF_FOLDER_NAME
   ,SCHEDULENAME
   ,RETRYCOUNT
   ,RECURORIGPRCSINST
   ,P_PRCSINSTANCE
   ,DISTSTATUS
   ,PRCSCATEGORY
   ,PRCSCURREXPIREDTTM

   ) values

   (:old.PRCSINSTANCE
   ,:old.JOBINSTANCE
   ,:old.MAINJOBINSTANCE
   ,:old.PRCSJOBSEQ
   ,:old.PRCSJOBNAME
   ,:old.PRCSTYPE
   ,:old.PRCSNAME
   ,:old.PRCSITEMLEVEL
   ,:old.MAINJOBNAME
   ,:old.MAINJOBSEQ
   ,:old.RUNLOCATION
   ,:old.OPSYS
   ,:old.DBTYPE
   ,:old.DBNAME
   ,:old.SERVERNAMERQST
   ,:old.SERVERNAMERUN
   ,:old.RUNDTTM
   ,:old.RECURNAME
   ,:old.OPRID
   ,:old.PRCSVERSION
   ,:old.RUNSTATUS
   ,:old.RQSTDTTM
   ,:old.LASTUPDDTTM

   ,:old.BEGINDTTM
   ,:old.ENDDTTM
   ,:old.RUNCNTLID
   ,:old.PRCSRTNCD
   ,:old.CONTINUEJOB
   ,:old.USERNOTIFIED
   ,:old.INITIATEDNEXT
   ,:old.OUTDESTTYPE
   ,:old.OUTDESTFORMAT
   ,:old.ORIGPRCSINSTANCE
   ,:old.GENPRCSTYPE
   ,:old.RESTARTENABLED
   ,:old.TIMEZONE
   ,:old.PSRF_FOLDER_NAME
   ,:old.SCHEDULENAME
   ,:old.RETRYCOUNT
   ,:old.RECURORIGPRCSINST
   ,:old.P_PRCSINSTANCE
   ,:old.DISTSTATUS
   ,:old.PRCSCATEGORY
   ,:old.PRCSCURREXPIREDTTM

   );

end;

/
